/**********************************************************************************
 * Copyright (c) 2026 borkdominik and others.
 *
 * This program and the accompanying materials are made available under the
 * terms of the MIT License which is available at https://opensource.org/licenses/MIT.
 *
 * SPDX-License-Identifier: MIT
 **********************************************************************************/
import type { Dimension, Point } from '@eclipse-glsp/protocol';

/**
 * The named connection points of a shape that has them - the four tips of a choice diamond.
 *
 * Lives here rather than beside the grammar because both ends need it: the server places a port on
 * each point and resolves a transition onto one, and the client draws them and reads back which one
 * was clicked. The literals are kept in step with the `ConnectionPoint` rule the language generator
 * produces from `transition-element.def.ts` - same four names, so a value crosses between the two
 * without translation.
 */
export type ConnectionPoint = 'NORTH' | 'EAST' | 'SOUTH' | 'WEST';

/** In drawing order, starting at the top and going clockwise. */
export const CONNECTION_POINTS: readonly ConnectionPoint[] = ['NORTH', 'EAST', 'SOUTH', 'WEST'];

/**
 * Separates a point's owner from its direction inside a port id.
 *
 * Long and unlovely on purpose: element ids are UUIDs generated by the model, but nothing stops one
 * from containing a plain `:`, and a port id has to be split back into its two halves exactly.
 */
const ID_SEPARATOR = '::point::';

/** The id of the port sitting on `point` of the element `ownerId`. */
export function connectionPointId(ownerId: string, point: ConnectionPoint): string {
    return `${ownerId}${ID_SEPARATOR}${point}`;
}

/**
 * Splits a port id back into the element it belongs to and the point it sits on, or `undefined` when
 * the id is not a port id at all - which is the normal answer for every other element in the diagram.
 */
export function parseConnectionPointId(id: string): { ownerId: string; point: ConnectionPoint } | undefined {
    const separator = id.lastIndexOf(ID_SEPARATOR);
    if (separator < 0) {
        return undefined;
    }
    const point = id.substring(separator + ID_SEPARATOR.length);
    if (!CONNECTION_POINTS.includes(point as ConnectionPoint)) {
        return undefined;
    }
    return { ownerId: id.substring(0, separator), point: point as ConnectionPoint };
}

/**
 * The shapes that offer named connection points, and how many they offer.
 *
 * A diamond offers all four of its tips. A bar offers the middle of each of its two long faces - the
 * faces the flow crosses - and nothing on its ends, which are a few pixels wide and would put two more
 * dots within touching distance of the corners.
 *
 * A box offers the middle of its left and right sides only. Those are the two sides an action takes its
 * pins on, and the flow through an action runs across it rather than down it, so a point on the top or
 * the bottom would be a place nothing is ever put.
 */
export type ConnectionPointLayout = 'diamond' | 'bar' | 'sides';

/**
 * Which points a shape of this layout and size actually has.
 *
 * Derived from the size rather than stored, because a bar's long faces *are* its size: standing one
 * upright is done by dragging it taller than it is wide, and its two points have to turn with it.
 * That also means a pin can be left pointing at a face the shape no longer has, which is why the
 * caller has to check against this list rather than trusting a stored point - see `createTransitionRelation`.
 */
export function offeredConnectionPoints(layout: ConnectionPointLayout, size: Dimension): readonly ConnectionPoint[] {
    if (layout === 'diamond') {
        return CONNECTION_POINTS;
    }
    // A box's two sides are its sides however it is dragged, so unlike a bar's these do not turn with
    // the proportions - the left of an action stays its left when the box is made taller than it is wide.
    if (layout === 'sides') {
        return ['WEST', 'EAST'];
    }
    return size.width >= size.height ? ['NORTH', 'SOUTH'] : ['WEST', 'EAST'];
}

/**
 * Where a point sits on a shape of `size`, relative to the shape's own origin.
 *
 * These are the tips of the diamond the view draws, which are also the midpoints of the shape's
 * bounding box - the one place the two agree, and why a point stays on the shape at any proportion.
 */
export function connectionPointPosition(size: Dimension, point: ConnectionPoint): Point {
    switch (point) {
        case 'NORTH':
            return { x: size.width / 2, y: 0 };
        case 'EAST':
            return { x: size.width, y: size.height / 2 };
        case 'SOUTH':
            return { x: size.width / 2, y: size.height };
        case 'WEST':
            return { x: 0, y: size.height / 2 };
    }
}

/**
 * The point of a shape of `size` that lies nearest `position`, both in the shape's own coordinates.
 *
 * Used to turn a click into a pin. Measured against the shape's own corners rather than a flat 45
 * degrees, so the changeover falls on the diamond's diagonal whatever its proportions - the same
 * comparison the client's tip anchor makes when no point has been pinned.
 */
export function nearestConnectionPoint(size: Dimension, position: Point): ConnectionPoint {
    const dx = position.x - size.width / 2;
    const dy = position.y - size.height / 2;
    if (Math.abs(dx) * size.height >= Math.abs(dy) * size.width) {
        return dx >= 0 ? 'EAST' : 'WEST';
    }
    return dy >= 0 ? 'SOUTH' : 'NORTH';
}
